### ISSUE TITLE
gRPC requests are failed for restarted modules

### ISSUE THREAD

**Issue by jollaman999** [hcloud-classic/hcc-piccolo#2]
If there are some restarted modules.
gRPC requests for that modules will fail.

I think we should re-create gRPC connection for each modules when the module is restarted.

@hcloudclassic

**Comment by hcloudclassic** [comment]
I saw that issues too.
The issue is fixed in https://github.com/hcloud-classic/hcc-piccolo/commit/a7a91f11a2064e639663694fc8d3642f911caadb
